export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_REQUESTED = "GET_CATEGORIES_REQUESTED"

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_REQUESTED = "GET_PRODUCTS_REQUESTED"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const BUY_THE_CART = "BUY_THE_CART"
export const BUY_THE_CART_REQUESTED = "BUY_THE_CART_REQUESTED"
export const EMPTY_THE_CART = "EMPTY_THE_CART"

export const SIGN_UP = "SIGN_UP"
export const SIGN_UP_REQUESTED = "SIGN_UP_REQUESTED"
export const SIGN_IN = "SIGN_IN"
export const SIGN_IN_REQUESTED = "SIGN_IN_REQUESTED"
export const AUTH_ERROR = "AUTH_ERROR"
export const SIGN_OUT = "SIGN_OUT"